# Generated by Django 4.1.7 on 2023-03-22 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Parks', '0001_initial'),
        ('ParkAdmin', '0005_customadminuser_username_alter_customadminuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customadminuser',
            name='manages_park',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Parks.park'),
        ),
    ]
