# Generated by Django 4.1.7 on 2023-02-20 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Park",
            fields=[
                ("park_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("location", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Benches",
            fields=[
                ("bench_id", models.AutoField(primary_key=True, serialize=False)),
                ("bench_title", models.CharField(max_length=30)),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "park_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Benches.park"
                    ),
                ),
            ],
        ),
    ]
