# Generated by Django 4.1.7 on 2023-02-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Benches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="benches",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
