# Generated by Django 4.1.7 on 2023-03-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Benches", "0003_alter_benches_qr_code_alter_benches_thumbnail_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="season_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SP", "Spring"),
                    ("SU", "Summer"),
                    ("FA", "Fall"),
                    ("WI", "Winter"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
