# Generated by Django 4.1.7 on 2023-03-22 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Parks', '0001_initial'),
        ('Benches', '0004_audio_season_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benches',
            name='park_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parks.park'),
        ),
    ]
