# Generated by Django 4.1.7 on 2023-03-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ParkAdmin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customadminuser",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
