# Generated by Django 4.1.7 on 2023-03-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ParkAdmin", "0003_alter_customadminuser_username"),
    ]

    operations = [
        migrations.RemoveField(model_name="customadminuser", name="username",),
    ]
