# Generated by Django 4.1.7 on 2023-03-22 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkAdmin', '0006_alter_customadminuser_manages_park'),
        ('Benches', '0005_alter_benches_park_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Park',
        ),
    ]
